package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * BmColor generated by hbm2java
 */
public class BmColor  implements java.io.Serializable {


     private int id;
     private String colorName;

    public BmColor() {
    }

	
    public BmColor(int id) {
        this.id = id;
    }
    public BmColor(int id, String colorName) {
       this.id = id;
       this.colorName = colorName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }




}


