package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * CkColor generated by hbm2java
 */
public class CkColor  implements java.io.Serializable {


     private String colorCode;
     private String colorName;
     private String colorJ;
     private Byte bmColorFamily;

    public CkColor() {
    }

	
    public CkColor(String colorCode) {
        this.colorCode = colorCode;
    }
    public CkColor(String colorCode, String colorName, String colorJ, Byte bmColorFamily) {
       this.colorCode = colorCode;
       this.colorName = colorName;
       this.colorJ = colorJ;
       this.bmColorFamily = bmColorFamily;
    }
   
    public String getColorCode() {
        return this.colorCode;
    }
    
    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }
    public String getColorJ() {
        return this.colorJ;
    }
    
    public void setColorJ(String colorJ) {
        this.colorJ = colorJ;
    }
    public Byte getBmColorFamily() {
        return this.bmColorFamily;
    }
    
    public void setBmColorFamily(Byte bmColorFamily) {
        this.bmColorFamily = bmColorFamily;
    }




}


