package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * Image generated by hbm2java
 */
public class Image  implements java.io.Serializable {


     private Integer id;
     private Integer itemId;
     private Integer variationId;
     private String imgName;
     private String imgUrl;

    public Image() {
    }

    public Image(Integer itemId, Integer variationId, String imgName, String imgUrl) {
       this.itemId = itemId;
       this.variationId = variationId;
       this.imgName = imgName;
       this.imgUrl = imgUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Integer getVariationId() {
        return this.variationId;
    }
    
    public void setVariationId(Integer variationId) {
        this.variationId = variationId;
    }
    public String getImgName() {
        return this.imgName;
    }
    
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }




}


