package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer itemId;
     private Integer brandId;
     private String itemName;
     private String url;
     private String serial;
     private Double price;
     private Double originalPrice;
     private String saleInfo;
     private String description;
     private String details;
     private String season;
     private String reference;
     private Double postage;
     private Double packing;
     private Boolean listed;
     private Boolean isDutiable;

    public Item() {
    }

    public Item(Integer brandId, String itemName, String url, String serial, Double price, Double originalPrice, String saleInfo, String description, String details, String season, String reference, Double postage, Double packing, Boolean listed, Boolean isDutiable) {
       this.brandId = brandId;
       this.itemName = itemName;
       this.url = url;
       this.serial = serial;
       this.price = price;
       this.originalPrice = originalPrice;
       this.saleInfo = saleInfo;
       this.description = description;
       this.details = details;
       this.season = season;
       this.reference = reference;
       this.postage = postage;
       this.packing = packing;
       this.listed = listed;
       this.isDutiable = isDutiable;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Integer getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Double getOriginalPrice() {
        return this.originalPrice;
    }
    
    public void setOriginalPrice(Double originalPrice) {
        this.originalPrice = originalPrice;
    }
    public String getSaleInfo() {
        return this.saleInfo;
    }
    
    public void setSaleInfo(String saleInfo) {
        this.saleInfo = saleInfo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getSeason() {
        return this.season;
    }
    
    public void setSeason(String season) {
        this.season = season;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public Double getPostage() {
        return this.postage;
    }
    
    public void setPostage(Double postage) {
        this.postage = postage;
    }
    public Double getPacking() {
        return this.packing;
    }
    
    public void setPacking(Double packing) {
        this.packing = packing;
    }
    public Boolean getListed() {
        return this.listed;
    }
    
    public void setListed(Boolean listed) {
        this.listed = listed;
    }
    public Boolean getIsDutiable() {
        return this.isDutiable;
    }
    
    public void setIsDutiable(Boolean isDutiable) {
        this.isDutiable = isDutiable;
    }




}


