package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * LbColor generated by hbm2java
 */
public class LbColor  implements java.io.Serializable {


     private short id;
     private Byte colorCode;
     private String colorLabel;
     private String colorJ;
     private Byte bmColorFamily;

    public LbColor() {
    }

	
    public LbColor(short id) {
        this.id = id;
    }
    public LbColor(short id, Byte colorCode, String colorLabel, String colorJ, Byte bmColorFamily) {
       this.id = id;
       this.colorCode = colorCode;
       this.colorLabel = colorLabel;
       this.colorJ = colorJ;
       this.bmColorFamily = bmColorFamily;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public Byte getColorCode() {
        return this.colorCode;
    }
    
    public void setColorCode(Byte colorCode) {
        this.colorCode = colorCode;
    }
    public String getColorLabel() {
        return this.colorLabel;
    }
    
    public void setColorLabel(String colorLabel) {
        this.colorLabel = colorLabel;
    }
    public String getColorJ() {
        return this.colorJ;
    }
    
    public void setColorJ(String colorJ) {
        this.colorJ = colorJ;
    }
    public Byte getBmColorFamily() {
        return this.bmColorFamily;
    }
    
    public void setBmColorFamily(Byte bmColorFamily) {
        this.bmColorFamily = bmColorFamily;
    }




}


