package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *ListedItems generated by hbm2java
 */
public class ListedItem  implements java.io.Serializable {


     private Integer id;
     private int itemId;
     private String listedName;
     private String comment;
     private Short category;
     private Byte season;
     private String theme;
     private String tags;
     private Date validTill;
     private Double salePrice;
     private String supplier;
     private String reference;
     private Double duties;
     private String buymaId;
     private String bmControl;
     private String bmBrandId;
     private Byte bmPcs;
     private Byte bmHasRefprice;
     private String itemImage1;
     private String itemImage2;
     private String itemImage3;
     private String itemImage4;
     private String itemImage5;
     private String itemImage6;
     private String itemImage7;
     private String itemImage8;
     private String itemImage9;
     private String itemImage10;
     private String itemImage11;
     private String itemImage12;
     private String itemImage13;
     private String itemImage14;
     private String itemImage15;
     private String itemImage16;
     private String itemImage17;
     private String itemImage18;
     private String itemImage19;
     private String itemImage20;

    public ListedItem() {
    }

	
    public ListedItem(int itemId) {
        this.itemId = itemId;
    }
    
    public ListedItem(int itemId, String listedName, String comment, Short category, Byte season, String theme, String tags, Date validTill, Double salePrice, String supplier, String reference, Double duties, String buymaId, String bmControl, String bmBrandId, Byte bmPcs, Byte bmHasRefprice, String itemImage1, String itemImage2, String itemImage3, String itemImage4, String itemImage5, String itemImage6, String itemImage7, String itemImage8, String itemImage9, String itemImage10, String itemImage11, String itemImage12, String itemImage13, String itemImage14, String itemImage15, String itemImage16, String itemImage17, String itemImage18, String itemImage19, String itemImage20) {
       this.itemId = itemId;
       this.listedName = listedName;
       this.comment = comment;
       this.category = category;
       this.season = season;
       this.theme = theme;
       this.tags = tags;
       this.validTill = validTill;
       this.salePrice = salePrice;
       this.supplier = supplier;
       this.reference = reference;
       this.duties = duties;
       this.buymaId = buymaId;
       this.bmControl = bmControl;
       this.bmBrandId = bmBrandId;
       this.bmPcs = bmPcs;
       this.bmHasRefprice = bmHasRefprice;
       this.itemImage1 = itemImage1;
       this.itemImage2 = itemImage2;
       this.itemImage3 = itemImage3;
       this.itemImage4 = itemImage4;
       this.itemImage5 = itemImage5;
       this.itemImage6 = itemImage6;
       this.itemImage7 = itemImage7;
       this.itemImage8 = itemImage8;
       this.itemImage9 = itemImage9;
       this.itemImage10 = itemImage10;
       this.itemImage11 = itemImage11;
       this.itemImage12 = itemImage12;
       this.itemImage13 = itemImage13;
       this.itemImage14 = itemImage14;
       this.itemImage15 = itemImage15;
       this.itemImage16 = itemImage16;
       this.itemImage17 = itemImage17;
       this.itemImage18 = itemImage18;
       this.itemImage19 = itemImage19;
       this.itemImage20 = itemImage20;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public String getListedName() {
        return this.listedName;
    }
    
    public void setListedName(String listedName) {
        this.listedName = listedName;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Short getCategory() {
        return this.category;
    }
    
    public void setCategory(Short category) {
        this.category = category;
    }
    public Byte getSeason() {
        return this.season;
    }
    
    public void setSeason(Byte season) {
        this.season = season;
    }
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }
    public Date getValidTill() {
        return this.validTill;
    }
    
    public void setValidTill(Date validTill) {
        this.validTill = validTill;
    }
    public Double getSalePrice() {
        return this.salePrice;
    }
    
    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }
    public String getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    public Double getDuties() {
        return this.duties;
    }
    
    public void setDuties(Double duties) {
        this.duties = duties;
    }
    public String getBuymaId() {
        return this.buymaId;
    }
    
    public void setBuymaId(String buymaId) {
        this.buymaId = buymaId;
    }
    public String getBmControl() {
        return this.bmControl;
    }
    
    public void setBmControl(String bmControl) {
        this.bmControl = bmControl;
    }
    public String getBmBrandId() {
        return this.bmBrandId;
    }
    
    public void setBmBrandId(String bmBrandId) {
        this.bmBrandId = bmBrandId;
    }
    public Byte getBmPcs() {
        return this.bmPcs;
    }
    
    public void setBmPcs(Byte bmPcs) {
        this.bmPcs = bmPcs;
    }
    public Byte getBmHasRefprice() {
        return this.bmHasRefprice;
    }
    
    public void setBmHasRefprice(Byte bmHasRefprice) {
        this.bmHasRefprice = bmHasRefprice;
    }
    public String getItemImage1() {
        return this.itemImage1;
    }
    
    public void setItemImage1(String itemImage1) {
        this.itemImage1 = itemImage1;
    }
    public String getItemImage2() {
        return this.itemImage2;
    }
    
    public void setItemImage2(String itemImage2) {
        this.itemImage2 = itemImage2;
    }
    public String getItemImage3() {
        return this.itemImage3;
    }
    
    public void setItemImage3(String itemImage3) {
        this.itemImage3 = itemImage3;
    }
    public String getItemImage4() {
        return this.itemImage4;
    }
    
    public void setItemImage4(String itemImage4) {
        this.itemImage4 = itemImage4;
    }
    public String getItemImage5() {
        return this.itemImage5;
    }
    
    public void setItemImage5(String itemImage5) {
        this.itemImage5 = itemImage5;
    }
    public String getItemImage6() {
        return this.itemImage6;
    }
    
    public void setItemImage6(String itemImage6) {
        this.itemImage6 = itemImage6;
    }
    public String getItemImage7() {
        return this.itemImage7;
    }
    
    public void setItemImage7(String itemImage7) {
        this.itemImage7 = itemImage7;
    }
    public String getItemImage8() {
        return this.itemImage8;
    }
    
    public void setItemImage8(String itemImage8) {
        this.itemImage8 = itemImage8;
    }
    public String getItemImage9() {
        return this.itemImage9;
    }
    
    public void setItemImage9(String itemImage9) {
        this.itemImage9 = itemImage9;
    }
    public String getItemImage10() {
        return this.itemImage10;
    }
    
    public void setItemImage10(String itemImage10) {
        this.itemImage10 = itemImage10;
    }
    public String getItemImage11() {
        return this.itemImage11;
    }
    
    public void setItemImage11(String itemImage11) {
        this.itemImage11 = itemImage11;
    }
    public String getItemImage12() {
        return this.itemImage12;
    }
    
    public void setItemImage12(String itemImage12) {
        this.itemImage12 = itemImage12;
    }
    public String getItemImage13() {
        return this.itemImage13;
    }
    
    public void setItemImage13(String itemImage13) {
        this.itemImage13 = itemImage13;
    }
    public String getItemImage14() {
        return this.itemImage14;
    }
    
    public void setItemImage14(String itemImage14) {
        this.itemImage14 = itemImage14;
    }
    public String getItemImage15() {
        return this.itemImage15;
    }
    
    public void setItemImage15(String itemImage15) {
        this.itemImage15 = itemImage15;
    }
    public String getItemImage16() {
        return this.itemImage16;
    }
    
    public void setItemImage16(String itemImage16) {
        this.itemImage16 = itemImage16;
    }
    public String getItemImage17() {
        return this.itemImage17;
    }
    
    public void setItemImage17(String itemImage17) {
        this.itemImage17 = itemImage17;
    }
    public String getItemImage18() {
        return this.itemImage18;
    }
    
    public void setItemImage18(String itemImage18) {
        this.itemImage18 = itemImage18;
    }
    public String getItemImage19() {
        return this.itemImage19;
    }
    
    public void setItemImage19(String itemImage19) {
        this.itemImage19 = itemImage19;
    }
    public String getItemImage20() {
        return this.itemImage20;
    }
    
    public void setItemImage20(String itemImage20) {
        this.itemImage20 = itemImage20;
    }




}


