package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * MasterSeason generated by hbm2java
 */
public class MasterSeason  implements java.io.Serializable {


     private byte seasonId;
     private String seasonName;

    public MasterSeason() {
    }

	
    public MasterSeason(byte seasonId) {
        this.seasonId = seasonId;
    }
    public MasterSeason(byte seasonId, String seasonName) {
       this.seasonId = seasonId;
       this.seasonName = seasonName;
    }
   
    public byte getSeasonId() {
        return this.seasonId;
    }
    
    public void setSeasonId(byte seasonId) {
        this.seasonId = seasonId;
    }
    public String getSeasonName() {
        return this.seasonName;
    }
    
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName;
    }




}


