package myApp;
// Generated 25-Jun-2021 10:28:37 by Hibernate Tools 4.3.1



/**
 * Variation generated by hbm2java
 */
public class Variation  implements java.io.Serializable {


     private Integer id;
     private Integer itemId;
     private String sku;
     private String url;
     private String colorCode;
     private String sizeName;
     private Boolean hasStock;
     private String availability;
     private Byte bmOrder;
     private Byte bmSearchsize;
     private String bmColName;
     private Byte bmColFamily;
     private Byte isListed;
     private String sizeInfo;
     private Integer lbProduct;
     private Integer lbSalableQty;

    public Variation() {
    }

    public Variation(Integer itemId, String sku, String url, String colorCode, String sizeName, Boolean hasStock, String availability, Byte bmOrder, Byte bmSearchsize, String bmColName, Byte bmColFamily, Byte isListed, String sizeInfo, Integer lbProduct, Integer lbSalableQty) {
       this.itemId = itemId;
       this.sku = sku;
       this.url = url;
       this.colorCode = colorCode;
       this.sizeName = sizeName;
       this.hasStock = hasStock;
       this.availability = availability;
       this.bmOrder = bmOrder;
       this.bmSearchsize = bmSearchsize;
       this.bmColName = bmColName;
       this.bmColFamily = bmColFamily;
       this.isListed = isListed;
       this.sizeInfo = sizeInfo;
       this.lbProduct = lbProduct;
       this.lbSalableQty = lbSalableQty;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public String getSku() {
        return this.sku;
    }
    
    public void setSku(String sku) {
        this.sku = sku;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getColorCode() {
        return this.colorCode;
    }
    
    public void setColorCode(String colorCode) {
        this.colorCode = colorCode;
    }
    public String getSizeName() {
        return this.sizeName;
    }
    
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }
    public Boolean getHasStock() {
        return this.hasStock;
    }
    
    public void setHasStock(Boolean hasStock) {
        this.hasStock = hasStock;
    }
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }
    public Byte getBmOrder() {
        return this.bmOrder;
    }
    
    public void setBmOrder(Byte bmOrder) {
        this.bmOrder = bmOrder;
    }
    public Byte getBmSearchsize() {
        return this.bmSearchsize;
    }
    
    public void setBmSearchsize(Byte bmSearchsize) {
        this.bmSearchsize = bmSearchsize;
    }
    public String getBmColName() {
        return this.bmColName;
    }
    
    public void setBmColName(String bmColName) {
        this.bmColName = bmColName;
    }
    public Byte getBmColFamily() {
        return this.bmColFamily;
    }
    
    public void setBmColFamily(Byte bmColFamily) {
        this.bmColFamily = bmColFamily;
    }
    public Byte getIsListed() {
        return this.isListed;
    }
    
    public void setIsListed(Byte isListed) {
        this.isListed = isListed;
    }
    public String getSizeInfo() {
        return this.sizeInfo;
    }
    
    public void setSizeInfo(String sizeInfo) {
        this.sizeInfo = sizeInfo;
    }
    public Integer getLbProduct() {
        return this.lbProduct;
    }
    
    public void setLbProduct(Integer lbProduct) {
        this.lbProduct = lbProduct;
    }
    public Integer getLbSalableQty() {
        return this.lbSalableQty;
    }
    
    public void setLbSalableQty(Integer lbSalableQty) {
        this.lbSalableQty = lbSalableQty;
    }




}


